# Generated by Django 6.1 on 2026-09-29 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9\\s-]{6,19}$', 'Enter a valid phone number.')]),
        ),
    ]
