# Generated by Django 6.1 on 2026-09-29 21:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^\\+?[0-9][0-9\\s-]{6,19}$', 'Enter a valid phone number.')])),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('Johor', 'Johor'), ('Kedah', 'Kedah'), ('Kelantan', 'Kelantan'), ('Melaka', 'Melaka'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Pulau Pinang', 'Pulau Pinang'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Selangor', 'Selangor'), ('Terengganu', 'Terengganu'), ('Kuala Lumpur', 'W.P. Kuala Lumpur'), ('Labuan', 'W.P. Labuan'), ('Putrajaya', 'W.P. Putrajaya')], max_length=32)),
                ('postcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Enter a valid 5-digit postcode.')])),
                ('country', models.CharField(choices=[('Malaysia', 'Malaysia')], default='Malaysia', max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'addresses',
                'ordering': ['-is_default', '-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user')],
            },
        ),
    ]
